### ISSUE TITLE
verification email not send to user when ticket created

### ISSUE THREAD

**Issue by jimmyzhu710** [justeat/ZendeskApiClient#213] opened 2019-07-10 01:53 UTC
Hi Team,

I am using api token to create the client as following:
  var client = new ZendeskApi.Client.ZendeskClient(
                        new Uri("https://webs.zendesk.com/api/v2"),
                        new ZendeskDefaultConfiguration("username here", "this is a password") );
Then I create a new ticket as following:
 var ticket = new Ticket()
            {
                Subject = model.Subject,
                Requester = new TicketRequester()
                {
                    Name = model.Email,
                    Email = model.Email
                },
                Comment = new TicketComment()
                {
                    Body = model.Message
                }
            };
           client.Tickets.Post(new TicketRequest()
            {
                Item = ticket
            });
But the end user did not receive any verification email. It still worked until this morning. Wondering if you can help. Thank you.

**Comment by jimmyzhu710** [comment] 2019-07-11 00:56
I think the end user receive a welcome email instead of a verification email. Just wondering if your API support the end_user to send a request and receive the verification to his email. like following https://develop.zendesk.com/hc/en-us/articles/360001068627

**Comment by corneliuskopp** [comment] 2019-07-11 15:02
Hello @jimmyzhu710! Glad you find our library (at least somewhat) useful!

One thing to start with, please beware that this is a public site. Please do not post authentication credentials here; they may be used by any random person browsing around here.

Secondly, how e-mail verification works is more a feature of the Zendesk instance; our library has not much stake in that. If your process worked until a few days ago and you have not updated the library code since then, it's not really an issue with the library. First port of call would, in my opinion, be to check that the user's e-mail is unverified at the moment.

If you have any issues with your Zendesk instance setup, contacting their support might be a better route.

If this doesn't really help, I may be misunderstanding your problem; would you mind elaborating where the issue is with the API client?

**Comment by jimmyzhu710** [comment] 2019-07-12 00:30
Hi Team,

Thank you for your response. My question actually is in Zendesk an end user can send anonymous request for ticket creation with API token like '{enduser_email_address}/token:{api_token}'. Then call the api 'POST /api/v2/requests.json'. Wondering if your api support this function or not.

**Comment by jimmyzhu710** [comment] 2019-07-12 01:13
Actually the end user doesn't need any authorization, he just calls the request api and specify the email address. An verification email will send to him. Wondering if you support this one

**Comment by mikerogers123** [comment] 2022-06-30 08:52
Hi @jimmyzhu710, apologies for the delay in getting back. Our team has recently taken some level of ownership of this repo so we can try to help here. 

If I understand your problem correctly, you would like to create tickets as an anonymous user (docs here: https://developer.zendesk.com/documentation/ticketing/managing-tickets/creating-and-managing-requests/#creating-anonymous-requests). If that's the case then there is a duplicate issue for this: https://github.com/justeat/ZendeskApiClient/issues/236. The upshot is that we need to add support for this as this API is not designed to support it as-is. There is a [TODO card](https://github.com/justeat/ZendeskApiClient/projects/2#card-83696093) for this, which our team will look at prioritising but until then PRs are still welcome.

For now will close this as there is a duplicate issue. Please let me know if I have misunderstood an we can reopen.

**Closed** 2022-06-30 08:52 UTC
